// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhbcosdvwzkyqbrcscyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoYmNvc2R2d3preXFicmNzY3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTg0MjAsImV4cCI6MjA2MTA5NDQyMH0.Y_pYe29pBA6wXf5hpFOa0dNJxe87xXv9CTEEm1tUeO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);